"""
Incident report export.

``build_report`` is a pure function: given all necessary inputs, it
returns a Markdown string suitable for download.  No I/O or side effects.
"""
from __future__ import annotations

from datetime import datetime


def build_report(
    scenario_key: str,
    label:        str,
    severity:     str,
    service:      str,
    stack:        str,
    alert:        str,
    metrics:      dict[str, str],
    logs:         list[dict],
    resolution:   str,
) -> str:
    """
    Build a Markdown incident report.

    Parameters
    ----------
    scenario_key:
        Scenario slug (used only for reference in the filename).
    label, severity, service, stack, alert:
        Scenario metadata.
    metrics:
        Dict with keys ``cpu``, ``error_rate``, ``p99_latency``.
    logs:
        Recent log rows from ``log_service.recent()``.
    resolution:
        Agent-generated resolution text.
    """
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    log_lines = "\n".join(
        f"[{l['ts'].strftime('%H:%M:%S')}] {l['level']:<5} {l['service']:<15} {l['message']}"
        for l in (logs or [])[:10]
    ) or "No logs captured"

    return (
        f"# Incident Report — {label}\n\n"
        f"**Generated:** {now}  \n"
        f"**Severity:** {severity}  \n"
        f"**Service:** {service}  \n"
        f"**Stack:** {stack}\n\n"
        f"## Alert\n\n```\n{alert}\n```\n\n"
        f"## Observed Metrics\n\n"
        f"| Metric | Value |\n|--------|-------|\n"
        f"| CPU | {metrics['cpu']} |\n"
        f"| Error Rate | {metrics['error_rate']} |\n"
        f"| p99 Latency | {metrics['p99_latency']} |\n\n"
        f"## Log Evidence\n\n```\n{log_lines}\n```\n\n"
        f"## AI-Assisted Resolution\n\n{resolution}\n\n"
        f"---\n*Generated by Synapse v4 — SRE Incident Co-Pilot*\n"
    )
